### ISSUE TITLE
Duplicate API Reference

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-wiki#24]
This page:
https://github.com/LiskHQ/lisk-wiki/wiki/Lisk-API-Reference
seems to be an outdated duplicate to this:
https://github.com/LiskHQ/lisk-wiki/wiki/API-Reference

Unfortunately, the outdated page is what google likes more:
https://www.google.de/search?q=lisk+api+docs&oq=lisk+api+docs

**Comment by Isabello** [comment]
Deleted the page.

**Comment by redsn0w0** [comment]
Changed the name from _API Refernce_ to **Lisk API Refernce**, now if you search ### Lisk API reference on google you will find the correct page.

**Comment by Isabello** [comment]
you didnt fix the side bar with this change.
