### ISSUE TITLE
Install script not found

### ISSUE THREAD

**Issue by mFarghaly** [LiskHQ/lisk-wiki#26]
Wgetting Install script returns 404 Not found. 
I was following instructions in **Getting started** page https://github.com/LiskHQ/lisk-wiki/wiki/Getting-Started
```
wget https://downloads.lisk.io/scripts/installLisk.sh
```
response
```
--2017-03-22 13:17:25--  https://downloads.lisk.io/scripts/installLisk.sh
Resolving downloads.lisk.io (downloads.lisk.io)... 94.237.40.215
Connecting to downloads.lisk.io (downloads.lisk.io)|94.237.40.215|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-22 13:17:26 ERROR 404: Not Found.

```

**Comment by mFarghaly** [comment]
I found other broken links, I won't open new issue. I will report them here:

- **Lisk Documentation** in [official resources](https://github.com/LiskHQ/lisk-wiki/wiki/Official-Resources)
- **Develop Blockchain APPs** in [official resources](https://github.com/LiskHQ/lisk-wiki/wiki/Official-Resources)

**Comment by karmacoma** [comment]
Thanks @mFarghaly, much appreciated. We have fixed the links now.
